print("alifattahi")

game_list = [" mine craft" , "counter strike" , "devil may cry" , "resident evil" , "hitman 2" , "call of duty" , "battle field" , "fortnite" ] 
print (game_list [+1])
print (game_list [+2])
print (game_list [+3])
print (game_list [-1])
print (game_list [-2])
print (game_list [-3])
print (len(game_list))
game_list.append("Pubg")
print (game_list)
game_list.remove ("fortnite")
print (game_list)
game_list.remove("resident evil")
print (game_list)
game_list.extend("hitman 2")
print (game_list)
game_list.insert(3 , "call of duty")
print (game_list)
game_list.pop(2)
print (game_list)

# name list (boy)

boy_names = [ "ali" , "mohammad" , "seperh" , "amir hossein" , "hossein" , "abolfazl" , "amir abbas" , "samiyar" , "mohammad taha" , "mehdi" , "navid"]
print (boy_names [+1])
print (boy_names [+2])
print (boy_names [+3])
print (boy_names [-1])
print (boy_names [-2])
print (boy_names [-3])
print (len(boy_names))
boy_names.append ("reza")
print (boy_names)
boy_names.remove ("reza")
print (boy_names)
boy_names.extend("ali")
print (game_list)
boy_names.insert(3 , "omid")
print (boy_names)
boy_names.pop(2)
print(boy_names)

# Girl name

girls_name = [ "sara" , "fateme" , "zahra" , "zeinab" , "maryam" , "atefe" , "setayesh" , "reyhane"]
print (len(girls_name))
print (girls_name [2])
print (girls_name [3])
print (girls_name [0])
print (girls_name [-2])
print (girls_name [-3])
print (girls_name [-5])
print(len(girls_name))
girls_name.append ("mlika")
print (girls_name)
girls_name.remove("setayesh")
print(girls_name)
girls_name.extend ("sara")
print (girls_name)
girls_name.insert (2 , "nazanin")
print (girls_name)
girls_name.pop (5)
print(girls_name)

#Team

team = [ "man city" , "real madrid" , "bayern" , "inter" , "liverpool" , "arsenal" , "barsa"]
print (team[1])
print (team[2])
print (team[0])
print (team[-1])
print (team[-2])
print (team[-3])
print (len(team))
team.append ("milan")
print (team)
team.remove ("arsenal")
print (team)
team.extend ("real madrid")
print (team)
team.insert (2 , "perspoles")
print (team)
team.pop ( 5 )
print (team)

#family

family = [ "fattahi" , "ragabi" ,  "mohammadi" , "hosseini" , "ahmadi" , "ghasemi" , "karimi" , "mousavi" , "jafari" , "bakhshean"]
print (len(family))
print(family [1])
print (family [2])
print(family [3])
print(family [-1])
print(family [-5])
print(family [-6])
family.append ("kazemi")
print (family)
family.remove ("mohammadi")
print (family)
family.extend ("fattahi")
print(family)
family.insert (2 , "hashhemi")
print (family)
family.pop (4)
print (family)
